# Numpy for Data Science


## Basic Questions

In [8]:
'''
1. Daily Temperature Analysis 🌡️

You recorded temperatures for 7 days:

temps = np.array([32, 35, 30, 29, 31, 36, 33])

👉 Tasks:

Find average temperature
Find hottest and coldest day
Count how many days temperature > 32
Normalize data (subtract mean from each value)
'''

#1
import numpy as np

temps = np.array([32, 35, 30, 29, 31, 36, 33])

avg_mean = np.mean(temps)
print(avg_mean)

avg= np.average(temps)
print(avg)

#-------------------------------------------------------------------#

#2
hottest = np.max(temps)
coldest = np.min(temps)

print(f"Hottest temperature is: {hottest} and Coldest temperature is: {coldest}")

#-------------------------------------------------------------------#

#3
count_days_temp_g_32 = np.sum(temps > 32)
print(count_days_temp_g_32)

#-------------------------------------------------------------------#

#4
normalized_temp =  temps - avg_mean 
print(normalized_temp) 


32.285714285714285
32.285714285714285
Hottest temperature is: 36 and Coldest temperature is: 29
3
[-0.28571429  2.71428571 -2.28571429 -3.28571429 -1.28571429  3.71428571
  0.71428571]


In [23]:
'''
2. Student Marks System 🎓

Marks of 5 students in 3 subjects:

marks = np.array([
    [85, 90, 88],
    [70, 60, 75],
    [95, 92, 96],
    [60, 65, 58],
    [88, 85, 90]
])

👉 Tasks:

Total marks per student
Average marks per subject
Find topper (index)
Add 5 grace marks using broadcasting
'''

#1
import numpy as np

marks = np.array([
    [85, 90, 88],
    [70, 60, 75],
    [95, 92, 96],
    [60, 65, 58],
    [88, 85, 90]
])

sum_marks = np.sum(marks, axis=1)
print(sum_marks)

#-------------------------------------------------------------------#

#2
avg_marks = np.mean(marks, axis=0)
print(avg_marks)

#-------------------------------------------------------------------#

#3
topper = np.argmax(sum_marks)
print(topper)

#-------------------------------------------------------------------#

#4
grace_marks =np.minimum( 5 + marks, 100) 
#or
grace_marks_where = np.where(marks<90 , marks+5, marks)
print(grace_marks)
print(grace_marks_where)

[263 205 283 183 263]
[79.6 78.4 81.4]
2
[[ 90  95  93]
 [ 75  65  80]
 [100  97 100]
 [ 65  70  63]
 [ 93  90  95]]
[[90 90 93]
 [75 65 80]
 [95 92 96]
 [65 70 63]
 [93 90 90]]


In [13]:
''' 
3. E-commerce Prices 🛒
prices = np.array([100, 200, 300, 400, 500])

👉 Tasks:

Apply 10% discount using broadcasting
Add 18% GST
Filter items with final price > 300
Replace prices < 150 with 150
'''

#1  
import numpy as np

prices = np.array([100, 200, 300, 400, 500])

discount =prices - (10 * prices)/100
print(discount)

#-------------------------------------------------------------------#

#2) 
gst = discount + (18 * discount)/100
print(gst)

#-------------------------------------------------------------------#

#3)
prices_g_150 = np.where(gst > 300, gst, 0)
print(prices_g_150)

#or

filtered = gst[gst>300]
print(filtered)

#-------------------------------------------------------------------#

#4) 
replace_prices_l_150 = np.where(prices<150, 150, prices)
print(replace_prices_l_150)

[ 90. 180. 270. 360. 450.]
[106.2 212.4 318.6 424.8 531. ]
[  0.    0.  318.6 424.8 531. ]
[318.6 424.8 531. ]
[150 200 300 400 500]


## Intermediate Questions


In [ ]:
'''4. Employee Salary Analysis 💼
salaries = np.array([25000, 30000, 28000, 40000, 50000, 32000])

👉 Tasks:

Increase all salaries by 10%
Find median salary
Extract salaries above average
Standardize salaries (z-score manually)'''

#1
import numpy as np

salaries = np.array([25000, 30000, 28000, 40000, 50000, 32000])

increased_salary = salaries + (salaries*10)/100
print(increased_salary)

#-------------------------------------------------------------------#

#2

median_salary = np.median(salaries)
print(median_salary)

#-------------------------------------------------------------------#

#3
avg_salary = np.mean(salaries)
print(avg_salary)
g_avg_salaries = salaries[salaries>avg_salary]
print(g_avg_salaries) 

#-------------------------------------------------------------------#

#4
standardized_salary = np.std(salaries)
print(standardized_salary)



[27500. 33000. 30800. 44000. 55000. 35200.]
31000.0
34166.666666666664
[40000 50000]
8454.124568648265


In [ ]:
'''5. Sales Data (Multi-Dimensional) 📊

Rows = stores, Columns = days

sales = np.array([
    [200, 220, 250, 270],
    [180, 190, 210, 230],
    [300, 320, 330, 350]
])

👉 Tasks:

Total sales per store
Best performing store
Day with highest total sales
Convert into 1D using flatten and compare with ravel'''

#1
import numpy as np

sales = np.array([
    [200, 220, 250, 270],
    [180, 190, 210, 230],
    [300, 320, 330, 350]
])

sales_per_store = np.sum(sales, axis=1)
print(sales_per_store)

#-------------------------------------------------------------------#

#2
best_Performing_store = np.argmax(sales_per_store)
print(best_Performing_store) 

#-------------------------------------------------------------------#

#3
day_with_highest_sales = np.argmax(np.sum(sales, axis=0))
print(day_with_highest_sales)

#-------------------------------------------------------------------#

#4

flatten_sales = sales.flatten()

#or 

ravel_sales = sales.ravel()

#comparison
flatten_sales[0] = 999 #this returns a copy of the original table and changes made in this will not take place in the original array
ravel_sales[1] = 899   #this returns a view of the original table and changes made in this will take place in the original array too

print(sales)
print(flatten_sales)
print(ravel_sales)


[ 940  810 1300]
2
3
[[200 899 250 270]
 [180 190 210 230]
 [300 320 330 350]]
[999 220 250 270 180 190 210 230 300 320 330 350]
[200 899 250 270 180 190 210 230 300 320 330 350]


## Advanced Questions


In [13]:
'''
7. Stock Price Analysis 📈
prices = np.array([100, 102, 101, 105, 110, 108, 115])

👉 Tasks:

Calculate daily returns
Find days where return > 2%
Rolling average (window = 3) manually
Normalize prices
'''
#1
import numpy as np

prices = np.array([100, 102, 101, 105, 110, 108, 115])

daily_returns = (prices[1:] - prices[:-1] )/ prices[:-1]
print(daily_returns)

#-------------------------------------------------------------------#

#2
return_g_2percent = np.where(daily_returns>0.02)
print(return_g_2percent)

#-------------------------------------------------------------------#

#3
rolling_avg = []
for i in range(len(prices) - 2):
    window = prices[i:i+3]
    rolling_avg.append( np.mean(window))

rolling_avg = np.array(rolling_avg)
print(rolling_avg)

#-------------------------------------------------------------------#

#4
normalized = (prices - prices.min())/(prices.max() - prices.min())
print(normalized)

#or

normalized_pro = (prices - prices.mean())/prices.std()
print(normalized_pro)

[ 0.02       -0.00980392  0.03960396  0.04761905 -0.01818182  0.06481481]
(array([2, 3, 5]),)
[101.         102.66666667 105.33333333 107.66666667 111.        ]
[0.         0.13333333 0.06666667 0.33333333 0.66666667 0.53333333
 1.        ]
[-1.15872851 -0.76306512 -0.96089681 -0.16957003  0.81958846  0.42392506
  1.80874694]


In [ ]:
'''  
8. Recommendation System (Similarity) 🤖
user1 = np.array([5, 4, 0, 1])
user2 = np.array([4, 0, 0, 1])

👉 Tasks:

Compute similarity using dot product
Compute cosine similarity manually
Find which user has higher preference intensity
'''

#1
import numpy as np

user1 = np.array([5, 4, 0, 1])
user2 = np.array([4, 0, 0, 1])

similarity = np.dot(user1 , user2)
print(similarity)

#-------------------------------------------------------------------#
#2
norm1 = np.linalg.norm(user1)
norm2 = np.linalg.norm(user2)

cos_sin = similarity/(norm1*norm2)
print(cos_sin)

#-------------------------------------------------------------------#
#3
if(norm1>norm2):
    print(f"User 1 has higher preference with : {norm1}")
else:
    print(f"User 2 has higher preference with : {norm2}")


21
0.7859052479933757
User 1 has higher preference with : 6.48074069840786


In [ ]:
'''  
9. Data Cleaning Scenario 🧹
data = np.array([10, 20, -999, 30, -999, 40])

👉 Tasks:

Replace -999 with mean of valid values
Remove outliers (< 15)
Reshape into 2 rows
Convert to float type
'''

import numpy as np

data = np.array([10, 20, -999, 30, -999, 40])

#1
clean_data = data[data!=-999]
print(clean_data)

mean_val = clean_data.mean()
data[data==-999] = mean_val
print(data)

#-------------------------------------------------------------------#
#2
remove_outliers = data[data>=15]
print(remove_outliers)

#-------------------------------------------------------------------#
#3
resized_data = np.reshape(data, (2,3))
print(resized_data)

#-------------------------------------------------------------------#
#4 
final_data = resized_data.astype(float)
print(final_data)

[10 20 30 40]
[10 20 25 30 25 40]
[20 25 30 25 40]
[[10 20 25]
 [30 25 40]]
[[10. 20. 25.]
 [30. 25. 40.]]
